---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v25.9.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        language_version: python3.11
