---
- name: Converge
  hosts: molecule_metadata
  become: yes

  vars:
    ansible_python_interpreter: python3
    metadata_owner: wazo
    metadata_environment: test
    metadata_service: metadata

  roles:
    - role: wazo.metadata

  post_tasks:
    - name: Assert variables are well set
      ansible.builtin.assert:
        that:
          - metadata_fqn == "wazo-test-metadata"
          - metadata_url == "metadata.test.wazo.cloud"
